### ISSUE TITLE
What is the latest build release for nginx? 

### ISSUE THREAD

**Issue by eric-mathison** [apache/incubator-pagespeed-ngx#1726] opened 2021-02-05 04:40 UTC
According to the Release notes, the version should be 1.14.36.1. But when getting the URL:
```
https://github.com/apache/incubator-pagespeed-ngx/archive/v1.14.36.1.tar.gz 
```
it resolves with a 404. What version is recommended to use?

**Comment by Lofesa** [comment] 2021-02-05 07:47
Hace you searchhed for this same issue?
Read #1656

**Comment by oschaaf** [comment] 2021-03-28 21:37
Closing as a duplicate of https://github.com/apache/incubator-pagespeed-ngx/issues/1730

**Closed by oschaaf** 2021-03-28 21:37 UTC
