### ISSUE TITLE
How to remove SRI?

### ISSUE THREAD

**Issue by fengerzh** [apache/incubator-pagespeed-ngx#1527] opened 2018-01-13 09:24 UTC
The origin html has tags like this:

`<link crossorigin="anonymous" integrity="sha256-3xE+QjMBXLBJxsPDEJK8ik0sOgONge/hn9f4/egRF5M=" rel="stylesheet" href="/assets/css/bootstrap.min.css" />`

But after pagespeed compress `css`, the content of css has changed, but `integrity` value still not changed, so that caused browser cannot correctly show content. How can we avoid this? Thanks!

**Comment by oschaaf** [comment] 2018-01-13 09:35
Thanks for the report. Considering you are using the term 'origin' I assume ngx_pagespeed is running in a  (reverse) proxy role. In that case I see no other option then to use url control [1] to disallow ngx_pagespeed to optimize those. Longer term, it would be nice if we could provide other options, like automatically skip these or optionally recompute the integrity hash.

[1] https://www.modpagespeed.com/doc/restricting_urls

**Comment by oschaaf** [comment] 2018-01-14 07:33
https://www.w3.org/TR/SRI/ states:

```
4. Proxies

Optimizing proxies and other intermediate servers which modify the responses must ensure
that the digest associated with those responses stays in sync with the new content. 
One option is to ensure that the integrity metadata associated with resources is updated. 
Another would be simply to deliver only the canonical version of resources for which a
page author has requested integrity verification.

To help inform intermediate servers, those serving the resources should send
along with the resource a Cache-Control header with a value of no-transform.
```

ngx_pagespeed should respect `Cache-Control: no-transform` by default:  https://www.modpagespeed.com/doc/configuration#notransform

**Comment by oschaaf** [comment] 2018-01-14 07:34
Closing this as a duplicate of https://github.com/apache/incubator-pagespeed-mod/issues/1687

**Closed by oschaaf** 2018-01-14 07:34 UTC
Labels: duplicate

**Comment by fengerzh** [comment] 2018-01-15 01:53
Personally I think to send a `no-transform` is not a good idea, because I DO want the css and js be combined into one file to save network bandwidth. The ideal way is still to combine them, but calculate a new SRI, or just simply strip the original SRI off from the html content, thus the browser will not complain SRI is incorrect.

**Comment by oschaaf** [comment] 2018-01-15 06:35
@fengerzh I agree, started fleshing out some thoughts over at https://github.com/apache/incubator-pagespeed-mod/wiki/Handling-Subresource-Integrity, feel free to join the effort
