### ISSUE TITLE
install from script fails due to new filename

### ISSUE THREAD

**Issue by arosenhagen** [apache/incubator-pagespeed-ngx#1521] opened 2018-01-08 11:48 UTC
The script at https://ngxpagespeed.com/install fails to install ngx_pagespeed due to the new name ```incubator-pagespeed-ngx-$VERSION```.

**Comment by oschaaf** [comment] 2018-01-08 12:25
The following patch on the script works for me:

``` diff
1 oschaaf@instance-1:~$ diff original.sh tmp.sh
617a618,619
>     nps_module_dir=$(unzip -qql "$nps_downloaded" | head -n1 | tr -s ' ' | cut -d' ' -f5-)
>     nps_module_dir="$BUILDDIR/${nps_module_dir::-1}"
```

(Should be applied to https://github.com/apache/incubator-pagespeed-ngx/blob/master/scripts/build_ngx_pagespeed.sh, I will create a PR later)

**Comment by jadatkins** [comment] 2018-01-08 12:26
The problem is here
https://github.com/apache/incubator-pagespeed-ngx/blob/ccaa714a85dd7b73d2b144e59167f4fa086ab53a/scripts/build_ngx_pagespeed.sh#L614-L619

In my case, line 614 expands to
```sh
run wget https://github.com/pagespeed/ngx_pagespeed/archive/v1.12.34.1-beta.zip -O /tmp/tmp.RvJfZmXZCb/ngx_pagespeed-1.12.34.1-beta.zip`
```
and https://github.com/pagespeed/ngx_pagespeed/archive/v1.12.34.1-beta.zip redirects to https://codeload.github.com/apache/incubator-pagespeed-ngx/zip/v1.12.34.1-beta

Everything up to line 618 works, but line 619 expands to
```sh
cd /root/ngx_pagespeed-1.12.34.1-beta
```

and here is the problem:
```
$ ls /root
incubator-pagespeed-ngx-1.12.34.1-beta
```

If you download that zip file, you will see that inside it is a folder called `incubator-pagespeed-ngx-1.12.34.1-beta` instead of `ngx_pagespeed-1.12.34.1-beta`, which is what it used to be.

I will submit a pull request to fix this.

**Comment by oschaaf** [comment] 2018-01-08 12:32
@jadatkins that analysis looks spot on to me. The repo got transferred last night... 
The diff I posted above tries to parse the directory name from zip, but I suspect it needs more work to land it. It would be great if you can help out with this and create a PR to mitigate the problem. 

Feel free to take the diff as a starting point (or not).

**Comment by jadatkins** [comment] 2018-01-08 12:35
Thanks @oschaaf, I can see how that works and it seems to work for me too. However, my work depends on automated scripts that download the script from GitHub, so being able to do it manually isn't really useful. Do you think it will be fixed today, or shall I fork the repository?

**Comment by oschaaf** [comment] 2018-01-08 12:36
I think this will get fixed today .. but currently I don't have write access to this repo which makes doing that right away kind of hard :-)

**Comment by jadatkins** [comment] 2018-01-08 12:38
thanks @oschaaf

**Comment by oschaaf** [comment] 2018-01-08 16:58
Should be fixed, please retry!

**Closed** 2018-01-08 16:57 UTC

**Comment by jadatkins** [comment] 2018-01-08 17:05
@oschaaf @jmarantz that seems to work, thank you!
